/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package demo

import org.scalatest.funsuite.AnyFunSuite

class AppSuite extends AnyFunSuite {
    test("App has a greeting") {
        assert(App.greeting().contains("Hello"))
    }
}
